//
//  MPSynchronousURLRequest.h
//  Hotspot Shield
//
//  Created by David Gatwood on 7/30/15.
//  Copyright © 2015 AnchorFree. All rights reserved.
//

#import <Foundation/Foundation.h>

/*!
    @abstract Synchronous URL helper
    @discussion
        NSURLConnection's sendSynchronousURLRequest method is problematic, and can cause
        fascinating crashes deep in the URL loading system when used.  This class
        avoids that problem by using NSURLConnection asynchronously and signalling the
        caller appropriately when the connection finishes or fails.
 */
@interface MPSynchronousURLRequest : NSObject

/*!
    @abstract Performs a URL request and returns the response data and metadata synchronously.
    @param request
        The URL request you wish to send.
    @param response
        On return, if non-NULL, the variable pointed to by this address is replaced by the
        NSURLResponse object generated by the request, or nil if the request did not
        receive a response.
    @param error
        On return, if non-NULL, the variable pointed to by this address is replaced by the
        NSError object generated by the request, or nil if the request did not produce an error.
 */
+ (NSData *)sendSynchronousRequest:(NSURLRequest *)request returningResponse:(NSURLResponse **)response error:(NSError **)error;

@end
